### ISSUE TITLE
Implement Star Injection

### ISSUE THREAD

**Issue by sweverett** [sweverett/Balrog-GalSim#5]
We're going to start using issues again! To start off with, we need to implement star injection. Sahar's star lists are found at: `/data/des20.b/data/sallam/Yanny-balrog/5sigma/`, where we can select what star density we want (for our fiducial 10% realization density, we would grab the list from `Extra_10_percent_16.5-26.5)`. There is a list with RA/DEC/MAG w/ zeropoint of 30 for all tiles.

Star injections will be done in SE same as galaxies. We will need new IO functions for Sahar's catalogs, write a new method for finding stars contained in a chip, and to update `add_gs_injection()` to take care of both (but allow for only one!). 

The tricky part seems to be with the GalSim config file. We can set multiple galaxy types (w/ 'galaxy' type 2 being a star) with the following:

```yaml
gal :
    type : List
    items : 
        - type : ngmixGalaxy
          # Existing galaxy injection
          #...
          index : [pos_1, pos_2, ...]
        
        - type: delta_function
           index : [pos_1, pos_2, ...]
           # Rest of star parameters, like mag/flux
    
    index : # Decide how to sample from type 1 vs type 2
```

But this also requires setting `gal[index]` to something sensible to determine when to injection from type 1 or type 2. So far, I haven't gotten the config to work using the above format while _also_ specifying exact image coordinates for stars / galaxies.
